version: 2

sources:
  - name: new_data
    database: BOOTCAMP_DEV_23152
    schema: new_data
    tables:
    - name: customer_details_silver
    - name: product_details_silver
    - name: order_details_silver
    - name: employee_details_silver
    - name: store_details_silver
    - name: campaign_details_silver
    - name: supplier_details_silver

  - name: DBT_SAIFSHAHUL_NEW_DATA
    tables: 
    - name: STG_CUSTOMERS
    - name: STG_PRODUCTS
    - name: STG_STORES
    - name: STG_SUPPLIER
    - name: STG_ORDERS
    - name: STG_MARKETING
    - name: STG_EMPLOYEES
      freshness:
        warn_after: {count: 12, period: hour}
      loaded_at_field: last_modified_date
    